import { SelectItem } from "primeng/api";

const FAKER_METHOD_OPTIONS: SelectItem[] = [
  { label: 'address.cityName', value: 'address.cityName' },
  { label: 'address.cityPrefix', value: 'address.cityPrefix' },
  { label: 'address.citySuffix', value: 'address.citySuffix' },
  { label: 'address.country', value: 'address.country' },
  { label: 'address.countryCode', value: 'address.countryCode' },
  { label: 'address.fullAddress', value: 'address.fullAddress' },
  { label: 'address.latitude', value: 'address.latitude' },
  { label: 'address.latLon', value: 'address.latLon' },
  { label: 'address.longitude', value: 'address.longitude' },
  { label: 'address.lonLat', value: 'address.lonLat' },
  { label: 'address.mailBox', value: 'address.mailBox' },
  { label: 'address.postcode', value: 'address.postcode' },
  { label: 'address.secondaryAddress', value: 'address.secondaryAddress' },
  { label: 'address.state', value: 'address.state' },
  { label: 'address.stateAbbr', value: 'address.stateAbbr' },
  { label: 'address.streetAddress', value: 'address.streetAddress' },
  { label: 'address.streetAddressNumber', value: 'address.streetAddressNumber' },
  { label: 'address.streetName', value: 'address.streetName' },
  { label: 'address.streetPrefix', value: 'address.streetPrefix' },
  { label: 'address.streetSuffix', value: 'address.streetSuffix' },
  { label: 'address.timeZone', value: 'address.timeZone' },
  { label: 'address.zipCode', value: 'address.zipCode' },
  { label: 'address.zipCodePlus4', value: 'address.zipCodePlus4' },


  { label: 'ancient.god', value: 'ancient.god' },
  { label: 'ancient.hero', value: 'ancient.hero' },
  { label: 'ancient.primordial', value: 'ancient.primordial' },
  { label: 'ancient.titan', value: 'ancient.titan' },

  { label: 'avatar.image', value: 'avatar.image' },

  { label: 'book.author', value: 'book.author' },
  { label: 'book.genre', value: 'book.genre' },
  { label: 'book.publisher', value: 'book.publisher' },
  { label: 'book.title', value: 'book.title' },

  { label: 'coffee.blendName', value: 'coffee.blendName' },
  { label: 'coffee.body', value: 'coffee.body' },
  { label: 'coffee.country', value: 'coffee.country' },
  { label: 'coffee.descriptor', value: 'coffee.descriptor' },
  { label: 'coffee.intensifier', value: 'coffee.intensifier' },
  { label: 'coffee.name1', value: 'coffee.name1' },
  { label: 'coffee.name2', value: 'coffee.name2' },
  { label: 'coffee.notes', value: 'coffee.notes' },
  { label: 'coffee.region', value: 'coffee.region' },
  { label: 'coffee.variety', value: 'coffee.variety' },

  { label: 'currency.code', value: 'currency.code' },
  { label: 'currency.name', value: 'currency.name' },

  { label: 'file.extension', value: 'file.extension' },
  { label: 'file.fileName', value: 'file.fileName' },
  { label: 'file.mimeType', value: 'file.mimeType' },


  { label: 'job.field', value: 'job.field' },
  { label: 'job.keySkills', value: 'job.keySkills' },
  { label: 'job.position', value: 'job.position' },
  { label: 'job.seniority', value: 'job.seniority' },
  { label: 'job.title', value: 'job.title' },

  { label: 'internet.botUserAgent', value: 'internet.botUserAgent' },
  { label: 'internet.botUserAgentAny', value: 'internet.botUserAgentAny' },
  { label: 'internet.domainName', value: 'internet.domainName' },
  { label: 'internet.domainSuffix', value: 'internet.domainSuffix' },
  { label: 'internet.domainWord', value: 'internet.domainWord' },
  { label: 'internet.emailAddress', value: 'internet.emailAddress' },
  { label: 'internet.getIpV4Address', value: 'internet.getIpV4Address' },
  { label: 'internet.getIpV6Address', value: 'internet.getIpV6Address' },
  { label: 'internet.getPrivateIpV4Address', value: 'internet.getPrivateIpV4Address' },
  { label: 'internet.getPublicIpV4Address', value: 'internet.getPublicIpV4Address' },
  { label: 'internet.httpMethod', value: 'internet.httpMethod' },
  { label: 'internet.image', value: 'internet.image' },
  { label: 'internet.ipV4Address', value: 'internet.ipV4Address' },
  { label: 'internet.ipV4Cidr', value: 'internet.ipV4Cidr' },
  { label: 'internet.ipV6Address', value: 'internet.ipV6Address' },
  { label: 'internet.ipV6Cidr', value: 'internet.ipV6Cidr' },
  { label: 'internet.macAddress', value: 'internet.macAddress' },
  { label: 'internet.password', value: 'internet.password' },
  { label: 'internet.port', value: 'internet.port' },
  { label: 'internet.privateIpV4Address', value: 'internet.privateIpV4Address' },
  { label: 'internet.publicIpV4Address', value: 'internet.publicIpV4Address' },
  { label: 'internet.safeEmailAddress', value: 'internet.safeEmailAddress' },
  { label: 'internet.slug', value: 'internet.slug' },
  { label: 'internet.url', value: 'internet.url' },
  { label: 'internet.userAgent', value: 'internet.userAgent' },
  { label: 'internet.uuid', value: 'internet.uuid' },
  { label: 'internet.uuidv3', value: 'internet.uuidv3' },
  { label: 'internet.webdomain', value: 'internet.webdomain' },

  { label: 'education.campus', value: 'education.campus' },
  { label: 'education.course', value: 'education.course' },
  { label: 'education.secondarySchool', value: 'education.secondarySchool' },
  { label: 'education.university', value: 'education.university' },


  { label: 'finance.bic', value: 'finance.bic' },
  { label: 'finance.creditCard', value: 'finance.creditCard' },
  { label: 'finance.iban', value: 'finance.iban' },

  { label: 'phone.cellPhone', value: 'phone.cellPhone' },
  { label: 'phone.phoneNumber', value: 'phone.phoneNumber' },

  { label: 'passaport.valid', value: 'passaport.valid' },

  { label: 'person.demonym', value: 'person.demonym' },
  { label: 'person.educationalAttainment', value: 'person.educationalAttainment' },
  { label: 'person.maritalStatus', value: 'person.maritalStatus' },
  { label: 'person.race', value: 'person.race' },
  { label: 'person.sex', value: 'person.sex' },

  { label: 'relationship.any', value: 'relationship.any' },
  { label: 'relationship.direct', value: 'relationship.direct' },
  { label: 'relationship.extended', value: 'relationship.extended' },
  { label: 'relationship.inLaw', value: 'relationship.inLaw' },
  { label: 'relationship.parent', value: 'relationship.parent' },
  { label: 'relationship.sibling', value: 'relationship.sibling' },
  { label: 'relationship.spouse', value: 'relationship.spouse' },

  { label: 'medical.diseaseName', value: 'medical.diseaseName' },
  { label: 'medical.hospitalName', value: 'medical.hospitalName' },
  { label: 'medical.medicineName', value: 'medical.medicineName' },
  { label: 'medical.symptoms', value: 'medical.symptoms' },

  { label: 'mood.emotion', value: 'mood.emotion' },
  { label: 'mood.feeling', value: 'mood.feeling' },
  { label: 'mood.tone', value: 'mood.tone' },

  { label: 'number.digit', value: 'number.digit' },
  { label: 'number.randomDigit', value: 'number.randomDigit' },
  { label: 'number.randomDigitNotZero', value: 'number.randomDigitNotZero' },
  { label: 'number.randomNumber', value: 'number.randomNumber' },

  { label: 'name.firstName', value: 'name.firstName' },
  { label: 'name.fullName', value: 'name.fullName' },
  { label: 'name.lastName', value: 'name.lastName' },
  { label: 'name.name', value: 'name.name' },
  { label: 'name.nameWithMiddle', value: 'name.nameWithMiddle' },
  { label: 'name.prefix', value: 'name.prefix' },
  { label: 'name.suffix', value: 'name.suffix' },
  { label: 'name.title', value: 'name.title' },
  { label: 'name.username', value: 'name.username' },
  { label: 'nation.capitalCity', value: 'nation.capitalCity' },
  { label: 'nation.flag', value: 'nation.flag' },
  { label: 'nation.isoCountry', value: 'nation.isoCountry' },
  { label: 'nation.isoLanguage', value: 'nation.isoLanguage' },
  { label: 'nation.language', value: 'nation.language' },
  { label: 'nation.nationality', value: 'nation.nationality' },

  { label: 'vehicle.carOptions', value: 'vehicle.carOptions' },
  { label: 'vehicle.carType', value: 'vehicle.carType' },
  { label: 'vehicle.color', value: 'vehicle.color' },
  { label: 'vehicle.doors', value: 'vehicle.doors' },
  { label: 'vehicle.driveType', value: 'vehicle.driveType' },
  { label: 'vehicle.engine', value: 'vehicle.engine' },
  { label: 'vehicle.fuelType', value: 'vehicle.fuelType' },
  { label: 'vehicle.licensePlate', value: 'vehicle.licensePlate' },
  { label: 'vehicle.make', value: 'vehicle.make' },
  { label: 'vehicle.makeAndModel', value: 'vehicle.makeAndModel' },
  { label: 'vehicle.manufacturer', value: 'vehicle.manufacturer' },
  { label: 'vehicle.model', value: 'vehicle.model' },
  { label: 'vehicle.standardSpecs', value: 'vehicle.standardSpecs' },
  { label: 'vehicle.style', value: 'vehicle.style' },
  { label: 'vehicle.transmission', value: 'vehicle.transmission' },
  { label: 'vehicle.upholstery', value: 'vehicle.upholstery' },
  { label: 'vehicle.upholsteryColor', value: 'vehicle.upholsteryColor' },
  { label: 'vehicle.upholsteryFabric', value: 'vehicle.upholsteryFabric' },
  { label: 'vehicle.vin', value: 'vehicle.vin' },

  { label: 'weather.description', value: 'weather.description' },
  { label: 'weather.temperatureCelsius', value: 'weather.temperatureCelsius' },
  { label: 'weather.temperatureFahrenheit', value: 'weather.temperatureFahrenheit' },

  { label: 'zodiac.sign', value: 'zodiac.sign' },

];


export default FAKER_METHOD_OPTIONS;
